# 28.10.24

ENEMY_TYPES = {
    0x00: "Chibibo (Goomba)",
    0x01: "Flattened Chibibo",
    0x02: "Pakkun (Piranha Plant)", 
    0x03: "Invisible Flying Bat",
    0x04: "Nokobon (Turtle)",
    0x05: "Nokobon's bomb",
    0x06: "Punching Hand",
    0x07: "Rising Platform (step-activated)",
    0x08: "1-3 Boss",
    0x09: "Jump-killable Enemy",
    0x0A: "Falling Platform",
    0x0B: "Left to Right Platform",
    0x0C: "Falling Tile (1-2)",
    0x0D: "None",
    0x0E: "Jumping Bat",
    0x0F: "Jumping Bat Death Animation",
    0x10: "Jumping Fish",
    0x11: "None",
    0x12: "None",
    0x13: "Rising Platform (step-activated)",
    0x14: "Auto-Rising Platform",
    0x15: "Jumping Bat Death Sound",
    0x16: "Fireball",
    0x17: "1-3 Boss Part (Counter-Clockwise)",
    0x18: "Delayed Attack Fireball",
    0x19: "Jumping Bat Death Sound",
    0x1A: "2-3 Water Boss",
    0x1B: "Higher Fireball",
    0x1C: "None",
    0x1D: "Jumping Sphinx Enemy",
    0x1E: "Lower Fireball",
    0x1F: "Flying Boss Ball",
    0x20: "Jumping Bat",
    0x21: "Explosion with 2 Bullets (Gunion)",
    0x22: "Low Boss Ball",
    0x23: "Bouncing Ball",
    0x24: "High Jumping Enemy",
    0x25: "Rising Killable Enemy",
    0x26: "None",
    0x27: "Explosion",
    0x28: "Right Moving Mushroom (passthrough)",
    0x29: "Left Moving Mushroom (passthrough)",
    0x2A: "Right Moving Heart (passthrough)",
    0x2B: "Left Moving Heart (passthrough)",
    0x2C: "Right Moving Star (passthrough)",
    0x2D: "Floating Flower (passthrough)",
    0x2E: "Ground Flower (passthrough)",
    0x2F: "Splitting Enemy",
    0x30: "Ground Scooting Enemy (unkillable)",
    0x31: "Fast Moving Enemy",
    0x32: "Boss Trigger",
    0x33: "Flipping Enemy",
    0x34: "Left Moving Star (passthrough)",
    0x35: "Falling Object",
    0x36: "End Level Falling Object",
    0x37: "None",
    0x38: "Diagonal Right Platform",
    0x39: "Diagonal Left Platform",
    0x3A: "Up-Down Two Ball Platform",
    0x3B: "Left-Right Two Ball Platform",
    0x3C: "Jumping Enemy",
    0x3D: "3C Death Animation",
    0x3E: "Death Sound",
    0x3F: "Gao (Fireball Sphinx)",
    0x40: "Gao Death Animation",
    0x41: "Death Sound",
    0x42: "Flying Bee",
    0x43: "Flying Bee Death Animation",
    0x44: "Death Sound",
    0x45: "Falling Arrow",
    0x46: "Nokobon Explosion",
    0x47: "Jumpable Platform Enemy",
    0x48: "Boss Music Moving Enemy",
    0x49: "Gira Shooter (from Pipe)",
    0x4A: "Gira (Bullet Bill)",
    0x4B: "Low Bullet",
    0x4C: "End Level Rising Platform",
    0x4D: "Auto End Level Rising Platform",
    0x4E: "None",
    0x4F: "Explosion",
    0x50: "Right Diagonal Bullet",
    0x51: "Rising Falling Killer Ball",
    0x52: "Ground Moving Shooter",
    0x53: "Jumping Enemy",
    0x54: "Circular Fireball",
    0x55: "Upside Down Pakkun",
    0x56: "Pionpi",
    0x57: "Dead-First Jumping Pionpi",
    0x58: "Low Fast Fireball",
    0x59: "Hidden 800 Points Trigger",
    0x5A: "Diagonal Left Bullet",
    0x5B: "Final Boss Trigger",
    0x5C: "Final Boss Fireball Explosion",
    0x5D: "Final Boss Upper Fireball",
    0x5E: "Final Boss Middle Fireball",
    0x5F: "Final Boss Lower Fireball",
    0x60: "Fast Final Boss (alt music)",
    0x61: "Alternative Boss",
    0x62: "Explosion to Final Boss",
    0x63: "Fast Diagonal Left Goomba",
    0x64: "Rising Dropping Enemy",
    0x65: "Goomba to Rising Platform",
    0x66: "None",
    0x67: "Boss Music Flying Enemy",
    0x68: "Rising Falling Enemy",
    0x69: "Static Enemy (Goomba)",
    0x6A: "Random Sprite Killer",
    0x6B: "Diagonal Star Transform Enemy",
    0x6C: "Temporary Ground Jumper",
    0x6D: "Rising Boss Music Trigger",
    0x6E: "Static Enemy",
    0x6F: "Continuous Ground Jumper",
    0x70: "Static Killer",
    0x71: "Exploding Double Fireball",
    0x72: "Continuous Ground Jumper",
    0x73: "Exploding Double Fireball",
    0x74: "Exploding Double Fireball",
    0x75: "Continuous Ground Jumper",
    0x76: "Random Sprite Killer",
    0x77: "Jump-Triggered Fireball",
    0x78: "Continuous Ground Jumper",
    0x79: "Boss Music Killer",
    0x7A: "Static Enemy",
    0x7B: "Slow Continuous Ground Jumper",
    0x7C: "Static Enemy",
    0x7D: "Random Sprite Killer",
    0x7E: "Static Enemy"
}
